# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=40)),
                ('senti', models.SmallIntegerField(choices=[('positive', 1), ('neutral', 0), ('negative', -1)], default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
        migrations.AddField(
            model_name='sentiword',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
