# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160317_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiword',
            name='senti',
            field=models.SmallIntegerField(choices=[(1, 'positive'), (0, 'neutral'), (-1, 'negative')], default=0),
        ),
    ]
